import Head from "next/head";
import useDnD from "@/hooks/useDnD";
import { FC, ReactNode, useState } from "react";
import { Effect } from "@/Components/Effect";

export default function Home() {
  let files = useDnD();
  console.log(files);

  let [itemArray, setItemArray] = useState<Array<ReactNode>>([]);
  return (
    <>
      <Head>
        <title>Dragging Canvas Text</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* main canvas */}
      <div
        id="wrapper"
        style={{
          position: "absolute",
          width: "100%",
          height: "100%",
          alignContent: "center",
          verticalAlign: "center",
          lineHeight: "100vh",
          opacity: 0,
          visibility: "hidden",
          background: "#F87171",
          color: "white",
          fontFamily: "cursive",
          fontSize: "100px",
          textAlign: "center",
        }}
      >
        drop here~
      </div>

      <button
        onClick={() =>
          setItemArray([
            ...itemArray,
            <Effect key={itemArray.length} name="new" />,
          ])
        }
        className="text-5xl m-10 font-bold absolute"
      >
        +
      </button>
      <main className="mx-auto border-2 border-red-400 relative h-screen w-[80%] p-0">
        {itemArray.map((fc, i) => fc)}
      </main>
    </>
  );
}
