import Head from "next/head";
import { Effect } from "@/Components/Effect";
import { TextField } from "@/Components/TextField";
import { useEffect, useState } from "react";
import useDnD from "@/hooks/useDnD";

export default function Home() {
  let files = useDnD();
  console.log(files);
  return (
    <>
      <Head>
        <title>Dragging Canvas Text</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* main canvas */}
      <div
        id="wrapper"
        style={{
          position: "absolute",
          width: "100%",
          height: "100%",
          alignContent: "center",
          verticalAlign: "center",
          flexGrow: "1",
          lineHeight: "100vh",
          opacity: 0,
          visibility: "hidden",
          background: "#123",
          color: "white",
          fontSize: "100px",
          textAlign: "center",
        }}
      >
        DROP HERE
      </div>

      <main className="mx-auto border-2 border-red-400 relative h-screen w-[50%] p-0">
        <TextField text="test" />
        <Effect name="Motion" />
        <Effect name="Glass" />
      </main>
    </>
  );
}
