import Head from "next/head";
import { Effect } from "@/Components/Effect";
import { TextField } from "@/Components/TextField";

export default function Home() {
  return (
    <>
      <Head>
        <title>Dragging Canvas Text</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* main canvas */}
      <main className="mx-auto border-2 border-red-400 relative h-screen w-[50%] p-0">
        <TextField text="test" />
        <Effect name="Motion" />
        <Effect name="Glass" />
      </main>
    </>
  );
}
